FROM node:20.16.0-alpine

WORKDIR /usr/app

ENV PNPM_HOME="/pnpm"

ENV PATH="$PNPM_HOME:$PATH"
ENV NODE_ENV=development

RUN npm i -g pnpm

WORKDIR /usr/app/client
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY . .

VOLUME [ "/usr/app/client/node_modules" ]

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
