services:
  client:
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:80"
  server:
    build:
      context: server
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:5000"