services:
  client:
    image: genorred/reenbit-chat:client
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./certbot/conf:/etc/letsencrypt:ro   # SSL-серты (readonly)
      - ./certbot/www:/var/www/certbot:rw     # webroot для ACME
    env_file:
      - .env
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
  server:
    image: genorred/reenbit-chat:server
    build:
      context: server
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5000"
    networks:
      - webnet
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >                        # обновляем каждые 12ч
      sh -c "trap exit TERM; while :; do
             certbot renew --webroot -w /var/www/certbot;
             sleep 12h;
      done"
    depends_on:
      - client
    networks:
      - webnet


networks:
  webnet:
    driver: bridge