FROM node:20.16.0-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm i -g pnpm

FROM base as build

ENV NODE_ENV=development
WORKDIR /usr/app

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

VOLUME [ "/usr/app/node_modules" ]

COPY . .
EXPOSE 8080

CMD ["pnpm", "run", "dev"]